services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: on-failure
    image: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--password=${SQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  wordpress:
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    build: requirements/wordpress
    image: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/ssl:/etc/ssl/certs
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ilymegy/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ilymegy/data/wordpress

networks:
  inception:
    driver: bridge
